jobs:

- job: win
  dependsOn:
  - macOs
  - linux
  pool:
    name: Hosted VS2017
  steps:
    - template: .azure/install.yml
    - template: .azure/tests.yml
    - template: .azure/test.yml
      parameters:
        path: tests/msgpack.spec.tests/msgpack.spec.tests.csproj
        framework: net46

    - task: PowerShell@2
      displayName: pack nuget package
      inputs:
        targetType: inline
        script: |
            $version = $(git describe --tags | %{$_ -replace '-([^g])', '.$1'})
            dotnet pack --no-build -v minimal -c Release /property:Version=$version /property:PackageOutputPath=$(Build.ArtifactStagingDirectory)
